import { Box, List, ListIcon, ListItem } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'
import { CheckCircleIcon, QuestionIcon } from '@chakra-ui/icons'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://ciesvi.vercel.app">ciesvi!</a>
        </h1>

        <p className={styles.description}>
          Get started. Upload your CSV. Do something with each of the rows.
        </p>

        <Box alignSelf="center" p="4" mb="4" borderRadius="md" borderColor="gray.300" borderWidth="1px">
          <List spacing={3}>
            <ListItem>
              <ListIcon as={CheckCircleIcon} color="green.500" />
              For each of row data, hit a HTTPS REST API (can add custom data too)
            </ListItem>
            <ListItem color="gray.400">
              <ListIcon as={QuestionIcon} color="yellow.500" />
              For each of row data, fill string template (probably soon)
            </ListItem>
            <ListItem color="gray.400">
              <ListIcon as={QuestionIcon} color="yellow.500" />
              For each of row data, transform it to new form (...soon?)
            </ListItem>
          </List>
        </Box>
        <br />

        <h6 className={styles.title} style={{ fontSize: '24px', border: '1px solid #0070f3', padding: '8px 12px', borderRadius: '16px' }}>
          <a href="https://ciesvi.vercel.app/upload">Upload my CSV</a>
        </h6>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
